version: "3.8"

services:
  nginx:
    image: staticfloat/nginx-certbot
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      CERTBOT_EMAIL: evgheni.calcutin@gmail.com
    volumes:
      - ./nginx:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
  dashboard:
    image: velesstan/dashboard
    restart: always
    ports:
      - 8080:80
  core:
    image: velesstan/core
    restart: always
    ports:
      - 3000:3000
    env_file: app.env
    depends_on:
      - database
  database:
    image: mongo:4.2.10
    restart: always
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./mongodb:/data/db
    command: mongod --config /etc/mongod.conf
    env_file: app.env
    ports:
      - "27017:27017"
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=180
      - SELF_UPDATE=true
      - IGNORE=database
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  letsencrypt:
